---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.2.4
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

# Box-and-whisker plot using Python + Turtle
### Oct 2019
### Credits and References: bit.ly/2cUdV5Y, bit.ly/2BtdoWI





# 🧮THE MATH PART

In this section of the jupyter notebook, your group will be performing the calculations for the box and whisker plot.



### 1. Set Up the Data


**Q: What data types are we working with?**  

🔢 For a Box-and-whisker plot, we can use either a **list of integers or a list of floats**.

**Q: What data are we working with?**  

✌️ We're going to give you two data sets.

Right now, you will work with `test_data`, a simple integer list.

`actual_data` is much longer. This is the actual data we want to plot.

```{python}
test_data = [6, 4, 5, 7, 1, 8, 2, 9, 3]
```

### 2. Sort the Data


**💻 TODO:** Write a function to sort a list so that it is in ascending order.

```{python}
# YOUR FUNCTION DEFINITION
```

**✅ Done?** Test your code by running your sort function. data_points should be sorted in ascending order.

```{python}
#Test your function with a function call here. 
```

### 3. Work out Calculations  


**💻 TODO:** Functions to calculate the median, minimum, maximum, range, lower quartile, and upper quartile. Feel free to add more cells if you need it.

```{python}
# YOUR FUNCTION DEFINITIONS
```

**✅ Done?** Test your code by running your functions on `test_data` below. Are the values the same if you calculate it by hand? You can also change sorted_test_data.

```{python}
#Test your function with a function call here. 
```

### 4. Great! Now let's repeat steps 1,2, and 3 with the actual data we want to graph.


We'll do step 1 for you. The 2 lines below will take one column from our social media use results (stored in a csv file) and turn it into a list.

The data we're using is a list of responses to this question: "How many social media accounts do you have?"

```{python}
from helpers import get_database_as_list
```

```{python}
actual_data = get_database_as_list('social_media_use.csv', 'Social media accounts', (0,100))
```

**💻 TODO:** Sort the list `actual_data` using your sort list function. Then create 5 variables to store the 5 calculations your functions will return.

```{python}
# YOUR FUNCTION CALLS
```

# 🎨 THE DRAWING PART

In this section of the jupyter notebook, your group will be drawing the calculations for the box and whisker plot.

We feel like you've already had enough experience doing the drawing with scatter plot, so we wrote the drawing code for you. However, there are some bugs that will keep this code from running like you'd expect.

**💻 TODO:** Find and fix the 4 bugs in the drawing code below.

```{python}
from turtle import *
from helpers import plot, scale, no_delay, restore_state_when_finished

BOX_HEIGHT = 100
```

### draw_min( )

```{python}
def draw_min():
    """
    Draws a vertical line at the min point of the dataset and labels the min below the line
    inputs: none
    outputs: none
    """
    
    with restore_state_when_finished():
        color("blue")
        penup()
        goto(scale(list_min, plot_settings['turtle_axis_domain'], plot_settings['data_domain']),BOX_HEIGHT/2)
        pendown()
        goto(scale(list_min, plot_settings['turtle_axis_domain'], plot_settings['data_domain']),-BOX_HEIGHT/2)
        penup()
        goto(scale(list_min, plot_settings['turtle_axis_domain'], plot_settings['data_domain']),(-3/4)*BOX_HEIGHT)
        write("Min", align="center")
        goto(scale(list_min, plot_settings['turtle_axis_domain'], plot_settings['data_domain']),(-7/8)*BOX_HEIGHT)
        write(list_min, align="center")
```
### draw_left_whisker( )

```{python}
def draw_left_whisker():
    """
    Draws a horizontal line between the min point and the Q1 point of the dataset.
    inputs: none
    outputs: none
    """
    
    with restore_state_when_finished():
        penup()
        goto(scale(list_min, plot_settings['data_domain'], plot_settings['turtle_axis_domain']),0)
        pendown()
        goto(scale(list_Q1, plot_settings['data_domain'], plot_settings['turtle_axis_domain']),0)
```

### draw_box( )

```{python}
def draw_box():
    """
    Draws a box of height `BOX_HEIGHT` beginning at Q1 and ending at Q3.
    inputs: none
    outputs: none
    """
    
    with restore_state_when_finished():
        color("red")
        penup()
        goto(scale(list_Q1, plot_settings['data_domain'], plot_settings['turtle_axis_domain']),-BOX_HEIGHT/2)
        pendown()
        goto(scale(list_Q3, plot_settings['data_domain'], plot_settings['turtle_axis_domain']),-BOX_HEIGHT/2)
        goto(scale(list_Q3, plot_settings['data_domain'], plot_settings['turtle_axis_domain']),BOX_HEIGHT/2)
        goto(scale(list_Q1, plot_settings['data_domain'], plot_settings['turtle_axis_domain']),BOX_HEIGHT/2)
        goto(scale(list_Q1, plot_settings['data_domain'], plot_settings['turtle_axis_domain']),-BOX_HEIGHT/2)
```

### draw_quartile_labels( )

```{python}
def draw_quartile_labels():
    """
    Adds labels for Q1 and Q3 below the box.
    inputs: none
    outputs: none
    """
    
    with restore_state_when_finished():
        penup()
        goto(scale(list_Q1, plot_settings['data_domain'], plot_settings['turtle_axis_domain']),(-3/4)*BOX_HEIGHT)
        write("list_Q1", align="center")
        goto(scale(list_Q1, plot_settings['data_domain'], plot_settings['turtle_axis_domain']),(-7/8)*BOX_HEIGHT)
        write(list_Q3, align="center",)
        goto(scale(list_Q3, plot_settings['data_domain'], plot_settings['turtle_axis_domain']),(-3/4)*BOX_HEIGHT)
        write("list_Q3", align="center")
        goto(scale(list_Q3, plot_settings['data_domain'], plot_settings['turtle_axis_domain']),(-7/8)*BOX_HEIGHT)
        write(list_Q1, align="center")
```

### draw_median( )

```{python}
def draw_median():
    """
    Draws a vertical line at the median point of the dataset and labels the median below the box.
    inputs: none
    outputs: none
    """
    
    with restore_state_when_finished():
        penup()
        color("green") #sets pen color to green
        goto(scale(list_median, plot_settings['data_domain'], plot_settings['turtle_domain']),BOX_HEIGHT/2)
        pendown()
        goto(scale(list_median, plot_settings['data_domain'], plot_settings['turtle_domain']),-BOX_HEIGHT/2)
        penup()
        goto(scale(list_median, plot_settings['data_domain'], plot_settings['turtle_domain']),(-3/4)*BOX_HEIGHT)
        write("Med", align="center")
        goto(scale(list_median, plot_settings['data_domain'], plot_settings['turtle_domain']),(-7/8)*BOX_HEIGHT)
        write(list_median, align="center")
```

### draw_max( )

```{python}
def draw_max():
    """
    Draws a vertical line at the max point of the dataset and labels the max below the line.
    inputs: none
    outputs: none
    """
    
    with restore_state_when_finished():
        color("blue")
        penup()
        goto(scale(list_max, plot_settings['data_domain'], plot_settings['turtle_axis_domain']),BOX_HEIGHT/2)
        pendown()
        goto(scale(list_max, plot_settings['data_domain'], plot_settings['turtle_axis_domain']),-BOX_HEIGHT/2)
        penup()
        goto(scale(list_max, plot_settings['data_domain'], plot_settings['turtle_axis_domain']),(-3/4)*BOX_HEIGHT)
        write("Max", align="center")
        goto(scale(list_max, plot_settings['data_domain'], plot_settings['turtle_axis_domain']),(-7/8)*BOX_HEIGHT)
        write(list_max, align="center")
```

### draw_right_whisker( )

```{python}
def draw_right_whisker():
    """
    Draws a horizontal line between the max point and the Q3 point of the dataset.
    inputs: none
    outputs: none
    """
    
    with restore_state_when_finished():
        penup()
        goto(scale(list_min, plot_settings['data_domain'], plot_settings['turtle_axis_domain']),0)
        pendown()
        goto(scale(list_Q1, plot_settings['data_domain'], plot_settings['turtle_axis_domain']),0)
```

<!-- #region -->
# 🧩PUTTING IT ALL TOGETHER

Here is where you can call the drawing functions your group writes.


We've already given you the function `plot()` in the `helpers.py` module with code to set up the settings and draw the axis of the plot. You need to pass in two things to this function:

* the data points you used as a `list`
* the label for the axis as a `string`

This function will return a `plot_settings` dictionary with the settings for the box and whisker plot.

💻 **TO DO:** Run the cell below to see what settings we're working with.

💻 **TO DO:** Then, add your drawing functions to draw the plot.
<!-- #endregion -->
```{python}
clearscreen()
plot_settings = {}
with no_delay():
    plot_settings = plot(actual_data, 'Social media accounts')
    #ADD YOUR FUNCTIONS HERE
plot_settings
```
